<?php

/**
 * @file
 * Contains entity_reference_override.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_reference_override_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_reference_override module.
    case 'help.page.entity_reference_override':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Entity reference with overridable title') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_usage_track_info().
 */
function entity_reference_override_entity_usage_track_info_alter(&$info) {
  // Track usage of entities related in entity_reference_override fields.
  // @see https://www.drupal.org/project/entity_usage
  if (!empty($info['entity_reference']['field_types'])) {
    $info['entity_reference']['field_types'][] = 'entity_reference_override';
  }
}
