field.field_settings.entity_reference_override:
  type: field.field_settings.entity_reference
  label: 'Entity reference override'
  mapping:
    override_label:
      type: string

field.storage_settings.entity_reference_override:
  type: field.storage_settings.entity_reference
  label: 'Entity reference override'

field.formatter.settings.entity_reference_override_label:
  type: field.formatter.settings.entity_reference_label
  mapping:
    override_action:
      label: 'Use custom text to'
      type: string

field.formatter.settings.entity_reference_override_entity:
  type: field.formatter.settings.entity_reference_entity_view
  mapping:
    override_action:
      label: 'Use custom text to'
      type: string
